language: generic 
sudo: required
services: 
  - docker

before_install:
  - docker build -t jogjawarrior/docker-react .

script:
  - docker run -e CI=true -p 80:80 jogjawarrior/docker-react

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1" #diambil dari url EBS dari AWS
  app: "docker-react" #diambil dari EBS AWS juga
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-622384535228" #Ambil dari S3 AWS
  bucket_path: "docker-react" #persis dengan nama app
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
